### ISSUE TITLE
a list of the forks in readme.md with info (like when they were released)

### ISSUE THREAD

**Issue by Ali00035v2** [SkiderKiller/Bounce-Killer#10]
Title...

also cracking LB forks that dont comply with GPL v3 is actually cool, take my star (some of them arent obfuscated 💀)

**Comment by RareCO** [comment]
In fact we dont know when the most of LBs in folder are released, we just find them out from Chinese liquidbounce community.
You can decompile some of them and u'll find the database of verify has been closed some time ago.

**Comment by RareCO** [comment]
Of course, we can try to do it.
