### ISSUE TITLE
Noteless Not work

### ISSUE THREAD

**Issue by xHX2134** [SkiderKiller/Bounce-Killer#11]
I cant log in

**Comment by xHX2134** [comment]
what should i tap in the uid

**Comment by RareCO** [comment]
DO NOT use small pad numbers
Please use the numbers on the top of ur keyboard.

**Comment by xHX2134** [comment]
> 不要使用小的键盘数字 请使用键盘顶部的数字。
so wats the uid

**Comment by RareCO** [comment]
And the noteless has been tested and I can login with any number.

**Comment by xHX2134** [comment]
> 不要使用小的键盘数字 请使用键盘顶部的数字。

0000 is not work

**Comment by xHX2134** [comment]
> 而且无记事已经测试过了，我可以使用任何号码登录。

wwwwwwwwwwwwwwat?

**Comment by RareCO** [comment]
Try 123

**Comment by xHX2134** [comment]
> 尝试 123

 verify failed

**Comment by RareCO** [comment]
with any logs?

**Comment by xHX2134** [comment]
where can i get the logs?

**Comment by xHX2134** [comment]
![13](https://user-images.githubusercontent.com/104604761/170419937-8baa39dd-2246-482d-aa11-bbec0cbef99c.png)

**Comment by RareCO** [comment]
which version

**Comment by xHX2134** [comment]
lastest release

**Comment by xHX2134** [comment]
[2022-05-26-3.log](https://github.com/SkiderKiller/Bounce-Killer/files/8776421/2022-05-26-3.log)

**Comment by RareCO** [comment]
Tell me the version number.

**Comment by xHX2134** [comment]
Noteless-220522-Cracked

**Comment by RareCO** [comment]
Use higher java version like 1.8.0_241

**Comment by xHX2134** [comment]
> Use higher java version like 1.8.0_241

ok i will try it thank u <3
