### ISSUE TITLE
About StarLight Cracked

### ISSUE THREAD

**Issue by KOFTWAR** [SkiderKiller/Bounce-Killer#4]
We didn't even have HWID verify !
                                                           ——StarLight Owner KOFTWAR

**Comment by KOFTWAR** [comment]
Everyone only need to pay for our config!

**Comment by RareCO** [comment]
Hello, please notice that the GPLv3 license forces you to open source, any forms of secondary closed source liquidbounce project will be pushed here and its NOT related to whether you have HWID verify.
If you have your project's open source link, please comment here and we will delete the "StarLight" folder.

**Comment by KOFTWAR** [comment]
还是用中文吧

我建议你们拥有自己的官网或网盘/Blog，访问Github对新人Hacker太过困难了

同时我支持你们的这个库，当代有太多换皮圈钱水影了

**Comment by RareCO** [comment]
Creating an official website or even a blog needs high maintenance cost.
If you want to browse the repository with higher performance, you can try the link below:
https://hub.fastgit.xyz/SkiderKiller/Bounce-Killer
